<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b1022c84-be9f-4d30-937b-835d2e1f8bf6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MethodLibrary\MethodLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pastel" Version="8.0.0" />
    <PackageReference Include="SoundFlow" Version="1.4.1" />
  </ItemGroup>

</Project>
